## Homework 04

In [109]:
from sklearn.preprocessing import StandardScaler
import numpy as np

In [88]:
data = [[0, 0], [0, 0], [1, 1], [1, 1]]

In [89]:
scaler = StandardScaler()

In [90]:
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [91]:
scaler.mean_

array([0.5, 0.5])

In [92]:
scaler.var_

array([0.25, 0.25])

In [93]:
scaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [94]:
scaler.transform([[2, 2]])

array([[3., 3.]])

## 自創

In [95]:
class MyStandardScaler:
    def __init__(self):
        self.mean_ = None
        self.var_ = None
        
    def fit(self, data):
        self.mean_ = np.mean(data, axis=0)
        self.var_ = np.var(data, axis=0)
        
    def transform(self, data):
        new_data = (np.array(data) - self.mean_)/(np.sqrt(self.var_))
        return new_data
    
    def fit_transform(self, data):
        self.fit(data)
        return self.transform(data)

In [96]:
myscaler = MyStandardScaler()

In [97]:
data

[[0, 0], [0, 0], [1, 1], [1, 1]]

In [98]:
myscaler.fit(data)

In [99]:
myscaler.mean_

array([0.5, 0.5])

In [100]:
myscaler.var_

array([0.25, 0.25])

In [101]:
myscaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [102]:
myscaler.transform([[2, 2]])

array([[3., 3.]])

## 測試 fit_transform

In [104]:
data2 = [[50, 100], [20, 30], [15, 5], [5, 5]]

In [105]:
scaler2 = StandardScaler()
myscaler2 = MyStandardScaler()

In [106]:
scaler2.fit_transform(data2)

array([[ 1.63978318,  1.6713433 ],
       [-0.1490712 , -0.12856487],
       [-0.4472136 , -0.77138922],
       [-1.04349839, -0.77138922]])

In [107]:
myscaler2.fit_transform(data2)

array([[ 1.63978318,  1.6713433 ],
       [-0.1490712 , -0.12856487],
       [-0.4472136 , -0.77138922],
       [-1.04349839, -0.77138922]])